
name: tests

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ububtu-latest
    steps:
      - uses: actions/checkout@2
      - run: cd auth && npm install && npm run test:ci 

  
